### ISSUE TITLE
errors on following paths /: /en-GB /: /zh-CN

### ISSUE THREAD

**Issue by theapplegates** [Harry-Yep/Notion-Blog-React#235]
I get the following error when I try to install the site. Not the exact error but close enough.
Export encountered errors on following paths /: /en-GB /: /zh-CN at /workspace/node_modules/next/dist/export/index.js 

I'm not a developer so my troubleshooting steps are basic. I did the following:
1. Deleted node_modules, .cache, package-lock.json and yarn.lock and then using yarn install or npm install depending on which lock file I deleted.
2. re-installed using yarn usually because I got an error about react 18 on a npm install.
3. Should I be using a certain version of nodejs? I can't find a recommended version. 
4. Does that error make sense to you? 
Can you point me in the right direction? My google searches have not found a solution.
I tried to remove all CN language items in any relevant  i18n file, but made a mess of things.
Thanks for any help you can provide.

**Comment by Harry-Yep** [comment]
Hi @theapplegates. 
Have you read the [documentation](https://docs.harrly.com/docs/notion-blog-react) and tried it again from the beginning?
Make sure that you fork or fetch the latest depository.
If you do so already, please let me know soon with a screenshot.

**Comment by Harry-Yep** [comment]
@theapplegates I have checked your fork repositories, [Notion-Blog-React22](https://github.com/theapplegates/Notion-Blog-React22) and [notion-nextjs-harry](https://github.com/theapplegates/notion-nextjs-harry) are fine.
However, please make sure you have set up your environment variables, if you do not know how to do, please see https://docs.harrly.com/docs/notion-blog-react#notion-api-preparation and https://docs.harrly.com/docs/notion-blog-react#notion-api-preparation

**Comment by theapplegates** [comment]
I have followed the documentation.
I forked the repo, then cloned the fork so I can click merge with your repo to keep them in sync.
I then put the notion api  variable and the NOTION_TABLE_SLUG variable into the .env file. The table slug I got after duplicating your table to my notion. I took the first 32 characters before the question mark as my table slug.
Now to attach some errors.
First I will explain in more detail what I did. Hope this makes sense. Just as an FYI I have tried this on several computers. I used Digital Ocean to start Fedora, Red Hat, Ubuntu, Debian and all fail. I am at a loss.

First I change the .git to a new setup using rm -rf .git and then entered  git init to start things. I then make my first commit after git add . and I upload the new repo.

Then I add the NOTION_API & NOTION_TABLE_SLUG to the .env.example, then I rename to .env
Then I do the install to test locally.
I use npm i and get the first set of errors.
Attached screen shot 1
I then use npm i --legacy-peer-deps and npm installs without errors.
Sometimes I use yarn install and I get no errors.

I then run npm dev
The npm install --legacy-peer-deps works fine, screenshot 2

run dev gives more errors

➜  clonedHarry-repo git:(main) ✗ npm run dev

> notion-blog-react@1.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/thor2/Documents/clonedHarry-repo/.env
wait  - compiling...
event - compiled client and server successfully in 2.3s (248 modules)
wait  - compiling / (client and server)...
wait  - compiling...
event - compiled client and server successfully in 1872 ms (327 modules)
wait  - compiling /500 (client and server)...
wait  - compiling...
event - compiled client and server successfully in 151 ms (330 modules)
error - Error: Request failed with status code 401
Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (/Users/thor2/Documents/clonedHarry-repo/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:172:19)
    at tryCatch (/Users/thor2/Documents/clonedHarry-repo/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/thor2/Documents/clonedHarry-repo/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/thor2/Documents/clonedHarry-repo/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/thor2/Documents/clonedHarry-repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/thor2/Documents/clonedHarry-repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/thor2/Documents/clonedHarry-repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/thor2/Documents/clonedHarry-repo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at serverSideTranslations (/Users/thor2/Documents/clonedHarry-repo/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:272:17)
wait  - compiling /_error (client and server)...
wait  - compiling...
event - compiled client and server successfully in 76 ms (331 modules)
^
See shreenshot 3

Now the strange part is I have a repo on vercel that works, well the home page works, when clicking on anything I get a serve error 500.

https://reimagined-octo-journey-notion.vercel.app

screenshot 4
<img width="1136" alt="Screenshot-4" src="https://user-images.githubusercontent.com/27178137/163808633-c96c7d99-82a5-4191-850b-cd6f9b621d6c.png">
<img width="996" alt="Screenshot-3" src="https://user-images.githubusercontent.com/27178137/163808635-75b71e40-d50c-499a-ad6f-711437171ea5.png">
<img width="980" alt="Screenshot 2" src="https://user-images.githubusercontent.com/27178137/163808637-841427d7-b671-47a8-a72b-7892f2ed3544.png">
<img width="768" alt="Screenshot-1" src="https://user-images.githubusercontent.com/27178137/163808639-c3b86f9d-6c14-4b01-b501-2976402c364b.png">

**Comment by theapplegates** [comment]
That should be all the errors.

**Comment by theapplegates** [comment]
I do add the .env to the vercel build. I forgot to mention it.

**Comment by Harry-Yep** [comment]
Hi.

This does seem to be a multilingual issue, unfortunately, we can't remove it right now, but you can hide it on the navbar. https://docs.harrly.com/docs/notion-blog-react/advanced-configuration#navbar

I would suggest you follow the below to check it yourself. 
- Using `yarn` instead of `npm`.
- Following the local deployment video if needed. 

https://user-images.githubusercontent.com/66008528/163817150-4292dcac-ce7e-4ff3-9b50-7578400a3532.mp4

**Comment by theapplegates** [comment]
It gives the same error. I eventide it in Visual Studio Code thinking it might help. It didn't. 
Here is the error when I run yarn dev

error - Error: Request failed with status code 401
Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:172:19)
    at tryCatch (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at serverSideTranslations (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:272:17)
error - Error: Request failed with status code 401
Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:172:19)
    at tryCatch (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at serverSideTranslations (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:272:17)
error - Error: Request failed with status code 401
Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:172:19)
    at tryCatch (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at /Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
    at serverSideTranslations (/Users/thor3/Downloads/Notion-Blog-React-main/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:272:17)

Error 401 is for authentication . Let me check with everything that needs authentication .

**Comment by theapplegates** [comment]
Oh, forgot to mention I did everything in the video. Thanks for the help.

**Comment by Harry-Yep** [comment]
I have checked your notion database and it's page. You have to add some contents inside your page, do not leave it blank. This might fix your issue.

**Comment by theapplegates** [comment]
That's crazy. Don't know how I managed that. I'll take a look as soon as I can. I appreciate your help.

**Comment by theapplegates** [comment]
I can't figure it out, but I don't want to waste your time. I'll figure it out eventually. It might take awhile. I'm probably doing something stupid.
Thanks for the help.
